### PR TITLE
RTL Support

### PR DESCRIPTION
**Pull request by yeganemehr**
RTL support by adding `rtl` class to `<body>` or `<html>`

### CODE REVIEW

**Comment by DimaSavchenko** [comment]
Hi @yeganemehr !
I have tried your solution and it look no quite well:

image

**Comment by yeganemehr** [comment]
Hi @DimaSavchenko
Sorry for my absent,
Actually It's looks good, but you did not feel that way because you tested in a left-to-right language (English) and It's looks strange to you, also you did not add `style="direction:rtl"` to your body.
Let's try it in Persian demo page:
awesome bootstrap checkbox demo

And finally let's mix your Persian demo page with [bootstrap-rtl](/morteza/bootstrap-rtl/) and see the result:
awesome bootstrap checkbox demo-rtl

**Comment by KillerSquid** [comment]
For my money JTCE's solution is way better.  Pure CSS and like 5 seconds to apply:
https://github.com/flatlogic/awesome-bootstrap-checkbox/issues/115

**Comment by yeganemehr** [comment]
OK @KillerSquid but did you ever develop one RTL page? I guess not!
adding `rtl` class for every checkbox in page is not cool at all.

**Comment by KillerSquid** [comment]
But being able to selectively apply it to ONLY the checkboxes where you need RTL support is more functionally sound than a blanket 'all page' approach.  Plus you can always just roll it into the existing CSS for all the checkboxes if you don't want to go through the hassle of typing three letters or programatically apply it to all checkboxes at runtime.
Also- there's absolutely no need to get snippy.  This is an open forum and people are allowed to post their ideas and opinions on software suggestions.  What works for you may not (and in my case, DID NOT) work for everyone so offering other suggestions on ways to achieve your goals is the WHOLE POINT OF GITHUB.

**Comment by cecilian** [comment]
Hello all,
is there any chance to see this merged in the not-so-far future?
Sure we can all patch the scss in our own projects to support RTL and it's not a big deal but it's a bit lame because we lose in terms of compatibility.

Also I agree with @yeganemehr that the "blanket" approach (styling applied to all elements of the page if the direction is RTL) works better especially if the plugin is being used in a multilingual site (so the same page can be served with different layouts).

This is a great plugin and it would be so helpful for it to support RTL out of the box.
Thank you!

**Pull request closed without merging**
