### PR TITLE
Sizing support

### PR DESCRIPTION
**Pull request by gandaldf**
Issue #65

### CODE REVIEW

**Comment by hellboy81** [comment]
Please accept commit and merge it into master!

**Comment by hellboy81** [comment]
why have you changed `css` but not `less`/`scss` ?

**Comment by gandaldf** [comment]
Because originally it was just a test... 😅

**Comment by hellboy81** [comment]
I have a problem with following [modified less file](https://gist.github.com/hellboy81/78ec807b970550152f793956afc13735)


In `build.less`:

```
@import "../../bootstrap/less/variables";
@import "../../bootstrap/less/mixins";
@import "../../font-awesome/less/variables";
@import "awesome-bootstrap-checkbox";
```

And then this file is minified and includen into main minified css

````html
<div class="aw-checkbox checkbox-lg">
  <label>
     <input type="checkbox" id="checkLarge" value="1">
   </label>
</div>
````

I have following issues

- checkbox has wrong size 
- check mark is not shown

With [this file](http://plnkr.co/edit/B4BatpwxCa2cBoYo0oEQ?p=preview) only checkbox position is wrong


>Because originally it was just a test.

Is there another way to create large checkboxes in Bootstrap? **And not a test!**

**Comment by DimaSavchenko** [comment]
Hi, @hellboy81! Could you please create PR? 
Thanks!

**Comment by jtreminio** [comment]
The CSS as-is creates elements that overlap each other:

image

Some simple changes can fix this:

```
.checkbox.checkbox-lg {
    margin-bottom: 5px;
}

.checkbox.checkbox-lg label::before {
    width: 46px;
    height: 46px;
    top: -3px;
}

.checkbox.checkbox-lg label::after {
    width: 46px;
    height: 46px;
    padding-left: 4px;
    font-size: 36px;
    left: 1px;
    top: -6px;
}

.checkbox.checkbox-lg label {
    padding-left: 34px;
    top: 5px;
    font-size: 30px;
}
```

which looks like this:

image

**Pull request closed without merging**
