### PR TITLE
Update for FontAwesome 5

### PR DESCRIPTION
**Pull request by sliceofbytes**
Updated scss file for FontAwesome 5

`$font-family-icon: 'Font Awesome\5 Free';`

&

`    &:checked + label::after {
            font-family: $font-family-icon;
            content: $check-icon;
			font-weight:600;
        }`

### CODE REVIEW

**Comment by vbjay** [comment]
For people just needing the CSS override

```css
.abc-checkbox input[type="checkbox"]:checked + label::after,
.abc-checkbox input[type="radio"]:checked + label::after {
    font-family: "Font Awesome 5 Free";
    content: "\f00c";
    font-weight: 900;
}
```

**Comment by ellenhutchings** [comment]
This would remove some workaround stuff I've had to put in to get this working again.

If requiring the font awesome 5 is a problem, perhaps the font-weight could be a variable too? Then it could be switched without having to override stuff

**Comment by sliceofbytes** [comment]
> This would remove some workaround stuff I've had to put in to get this working again.
> 
> If requiring the font awesome 5 is a problem, perhaps the font-weight could be a variable too? Then it could be switched without having to override stuff

Yes that is probably a better fix going forward. I'll adjust my pull request.

**Comment by ellenhutchings** [comment]
Considering we now have a bootstrap 5 update, could we please merge this in and support font awesome 5, which is a version behind already?

**Pull request closed without merging**
